"""Generate Cline-friendly instructions.md from spec"""
from pathlib import Path
from typing import Dict, Any
import json
import logging

logger = logging.getLogger(__name__)


def build_instructions(spec: Dict[str, Any], repo_dir: str = "repo") -> str:
    """
    Generate Cline-friendly instructions.md.
    
    Args:
        spec: The spec.json dictionary
        repo_dir: Relative path to repository directory
    
    Returns:
        Instructions markdown content
    """
    project = spec.get("project", {})
    stack = spec.get("stack", [])
    components = spec.get("components", {})
    
    project_name = project.get("name", "Generated Project")
    description = project.get("description", "")
    
    nodes = components.get("nodes", [])
    connections = components.get("connections", [])
    
    # Build component descriptions
    component_list = []
    for node in nodes:
        name = node.get("name", "Unknown")
        node_type = node.get("type", "generic")
        framework = node.get("framework", "")
        
        comp_desc = f"- **{name}** (type: {node_type}"
        if framework:
            comp_desc += f", framework: {framework}"
        comp_desc += ")"
        
        component_list.append(comp_desc)
    
    # Build connection descriptions
    connection_list = []
    for conn in connections:
        connection_list.append(f"- {conn['from']} → {conn['to']}")
    
    instructions = f"""# Architecture Generation Instructions

## Goal

Generate a complete codebase for **{project_name}** based on the architecture specification.

{description if description else "This project follows a modern full-stack architecture pattern."}

## Stack

The project should use the following technologies:
{chr(10).join(f"- {tech}" for tech in stack)}

## Architecture Components

The system consists of the following components:

{chr(10).join(component_list) if component_list else "- No specific components defined"}

## Component Connections

{chr(10).join(connection_list) if connection_list else "- No explicit connections defined"}

## Repository Structure

Generate all code into the `{repo_dir}/` directory. The structure should be appropriate for the selected stack.

### Example Structure (Next.js + FastAPI)

```
{repo_dir}/
├── frontend/          # Next.js application
│   ├── src/
│   ├── package.json
│   └── next.config.ts
├── backend/           # FastAPI application
│   ├── main.py
│   ├── requirements.txt
│   └── Dockerfile
├── README.md          # REQUIRED: Setup and run instructions
└── docker-compose.yml # Optional but recommended
```

## Hard Constraints

1. **NO SECRETS**: Never hardcode API keys, tokens, or credentials. Use environment variables.
2. **README.md REQUIRED**: Must include a README.md with:
   - Project description
   - Installation steps
   - How to run the application
   - Environment variable setup
3. **DO NOT DELETE**: Do not delete or modify existing files unless explicitly required.
4. **COMPLETE IMPLEMENTATION**: Generate working, runnable code - not just stubs.

## Acceptance Checklist

Before marking as complete, verify:
- [ ] README.md exists with run instructions
- [ ] At least one source file generated (excluding .git)
- [ ] No hardcoded secrets
- [ ] Environment variables properly documented
- [ ] Code is syntactically valid

## Source of Truth

Refer to `spec.json` in the input directory for the complete architecture specification.
The spec.json file contains the authoritative structure and requirements.

---

**Generated by Architex Agent Runner**
"""
    
    return instructions


def write_instructions(instructions: str, output_path: Path) -> None:
    """Write instructions.md to file"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(instructions)
    logger.info(f"Wrote instructions.md to {output_path}")
